#!/bin/bash

# CISC 327, fall 2016
# Assignment 6
# For Prof James Cordy
# Due 9 Dec 2016
# Author: Team Onk (Kevin Chan, Niki Lin, Simon Zhang)

# Weekly script for SimBank
# Please see folder_hierarchy.jpg for the expected folder hierarchy for which this script uses.

# runs the daily script for every day of the week (1 to 5)
# assumes that all input files exist

# command line arguments:
# $1 = week number 


# if week number is not entered in parameter 1
if [ -z ${1} ]
then
	echo "Please enter a week number in parameter 1."
	exit 1
fi

# ask for confirmation
read -p "Are you sure you want to run the weekly script for week "$1"? [y/n]" -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
	exit 1
fi

week=$1

echo "Executing the weekly script for week "$1"..."

for i in $(seq 1 5)
do
	echo 'y' | ./dailyScript $week $i
done